[package]
name = "isec-master-thesis-template"
version = "1.0.0"
entrypoint = "src/lib.typ"
authors = ["ecomaikgolf.com"]
license = "MIT"
description = "ISEC TUGraz Master's Thesis Template"
repository = "https://github.com/ecomaikgolf/typst-isec-master-thesis-template/"
keywords = ["ISEC", "Institute of Information Security", "IAIK", "TUGraz", "Graz University of Technology", "thesis", "template", "Master Thesis"]
categories = ["thesis"]
disciplines = ["computer-science", "engineering"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "thesis.typ"
